### PR TITLE
initial setup of the group-edge Ansible Edge Automation WG space

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <admiller@redhat.com>

### CODE REVIEW

**Comment by gotmax23** [comment]
Should the references to the Security WG be replaced?

**Comment by maxamillion** [comment]
@gotmax23 yes, that was an oversight on my part because I copied that one as a starting point ... will fix.

**Comment by maxamillion** [comment]
@gotmax23 I added the calendar yaml but I don't know how to generate the ical file

**Comment by gotmax23** [comment]
> @gotmax23 I added the calendar yaml but I don't know how to generate the ical file

1. `pip(x) install yaml2ical` or `sudo dnf install python3-yaml2ical` if you run Fedora ;)
2. make -C meetings

**Comment by maxamillion** [comment]
> > @gotmax23 I added the calendar yaml but I don't know how to generate the ical file
> 
>     1. `pip(x) install yaml2ical` or `sudo dnf install python3-yaml2ical` if you run Fedora ;)
> 
>     2. make -C meetings

When I ran `make -C meetings` it changed a *lot* of files .... is it safe to commit all the changes?

**Comment by Andersson007** [comment]
@maxamillion is this PR still relevant? Trying to tidy up/revitalize work here

**Comment by samccann** [comment]
We are going to be archiving this ansible/community repo so going to close this PR as we won't accept future changes here. See https://forum.ansible.com/t/moving-ansible-community-content-to-ansible-community/1928/7 for details on the move plans.

**Pull request closed without merging**
