### PR TITLE
Regenerate ICS files

### PR DESCRIPTION
**Pull request by gotmax23**
The community meeting time was changed, so we need to regenerate the iCalendar files.

### CODE REVIEW

**Comment by gotmax23** [comment]
Would something like

``` patch
diff --git a/ansible_community_meetings.ics b/ansible_community_meetings.ics
index 955a8d0..0a58208 100644
--- a/ansible_community_meetings.ics
+++ b/ansible_community_meetings.ics
@@ -32,8 +32,10 @@ LOCATION:#ansible-azure
 END:VEVENT
 BEGIN:VEVENT
 SUMMARY:Community working group
-DTSTART;VALUE=DATE-TIME:20210512T180000Z
+DTSTART;VALUE=DATE-TIME:20221116T190000Z
 DURATION:PT1H
+DTSTAMP;VALUE=DATE-TIME:20221109T200050Z
+UID:communityworkinggroup-20221116
 RRULE:FREQ=WEEKLY
 DESCRIPTION:Project:  Community working group\nChair:  John Barker (gundal
  ow)\nDescription:  \nDiscuss everything related to Ansible Community and C
diff --git a/meetings/ical/community.ics b/meetings/ical/community.ics
index 30f779c..2b9ab01 100644
--- a/meetings/ical/community.ics
+++ b/meetings/ical/community.ics
@@ -3,8 +3,10 @@ VERSION:2.0
 PRODID:-//yaml2ical agendas//EN
 BEGIN:VEVENT
 SUMMARY:Community working group
-DTSTART;VALUE=DATE-TIME:20210512T180000Z
+DTSTART;VALUE=DATE-TIME:20221116T190000Z
 DURATION:PT1H
+DTSTAMP;VALUE=DATE-TIME:20221109T200050Z
+UID:communityworkinggroup-20221116
 RRULE:FREQ=WEEKLY
 DESCRIPTION:Project:  Community working group\nChair:  John Barker (gundal
  ow)\nDescription:  \nDiscuss everything related to Ansible Community and C

```

be better to avoid changing all of the other files?

**Comment by Andersson007** [comment]
@gotmax23 thanks!
there's a merge conflict. I think someone worked in parallel, could you please resolve them?

**Comment by Andersson007** [comment]
@gotmax23 any updates?

**Comment by gotmax23** [comment]
I'm busy today, so feel free to go ahead and submit a new PR.

**Pull request closed without merging**
