### PR TITLE
Move Docs WG meeting to DST

### PR DESCRIPTION
**Pull request by samccann**
Moving meeting to account for start of DST in Europe.

Also need to:

- [x]  edit https://github.com/ansible/community/wiki/Docs to say 15:00 UTC.

- [ ] change matrix reminder bot to move the DING DING DING reminder  to 14:00 UTC (on hour before the meeting)
- [ ]  Change the room cyb-clock-clone meeting reminders every 15 minutes during the meeting time. (see https://github.com/anoadragon453/matrix-reminder-bot)

### CODE REVIEW

**Review by gundalow — CHANGES_REQUESTED** [review]
Need to run `make` and then revert the other files and other entries in `ansible_community_meetings.ics`

**Comment by cybette** [comment]
also meetings/README.md needs to be updated :)

**Comment by samccann** [comment]
@gundalow I get the following error w/ make:

~/community/meetings (dawgs-dst) $ make all
yaml2ical -y . -i ./ical/ -f
make: yaml2ical: No such file or directory
make: *** [Makefile:2: all] Error 127

**Comment by samccann** [comment]
ready_for_review

**Review by felixfontein — APPROVED** [review]

**Pull request merged**
