### PR TITLE
Add slide deck for 3.0.0 community update

### PR DESCRIPTION
**Pull request by dmsimard**
For contributor summit presentation on March 9th.

### CODE REVIEW

**Comment by gundalow** [comment]
Minor suggestion, in the timelines maybe have ansible-core/base in a different color?

**Review by gundalow — APPROVED** [review]
This is great, thank you.
Minor suggestion, in the timelines maybe have ansible-core/base in a different color? Though if that's a pain, feel free to ignore.

**Comment by dmsimard** [comment]
@gundalow thanks for taking a look! I think different colors would be a good idea but the way I implemented the timeline is kinda hacky over multiple images so I'd need to update all of them -- I'll merge as-is for now but will update it in time if I have a chance.

**Comment by gundalow** [comment]
> @gundalow thanks for taking a look! I think different colors would be a good idea but the way I implemented the timeline is kinda hacky over multiple images so I'd need to update all of them -- I'll merge as-is for now but will update it in time if I have a chance.

I assumed as much. What you've made is an infinite improvement over what we have.

One of the ideas of using Git to store the decks is to make it so that anyone can update them over time.

**Pull request merged**
